### ISSUE TITLE
An error has occurred while launching the default browser.

### ISSUE THREAD

**Issue by V-jay-vj** [igorskyflyer/vscode-open-in-browser#11]
Issue Type: <b>Bug</b>

An error has occurred while launching the default browser.

Extension version: 1.0.2
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (3.31GB free)|
|Process Argv|--crash-reporter-id 076e1079-3b9b-46bc-b011-f5596a3b4810|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30301613
vscorehovct:30302760
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by janstieler** [comment]
Hi,
I have the same error. How have you solved this?
I ask because you closed this issue so I think you have solved it.

Cheers

**Comment by igorskyflyer** [comment]
> Hi, I have the same error. How have you solved this? I ask because you closed this issue so I think you have solved it.
> 
> Cheers

Hi, I didn't close the issue, the person who opened it closed it but regarding the issue, the development of Visual Studio Code extensions which I do like doing 😁 takes time, time that I currently can't invest since it doesn't pay my bills 😕 I am planning to release a new version of this extension with this particular issue - and others - fixed but I cannot tell you the exact timeframe for it to happen.
Hopefully I will find some time soon and release the new version of the extension since I use it too. 😅
